name: Docker Build and Run

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Docker Image
      run: |
        docker build . -t needle-in-a-haystack

    - name: Run Docker Container
      run: |
        docker run --entrypoint pytest -t needle-in-a-haystack
